### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by svanharmelen** [davidmz/go-pageant#1]
Hi @davidmz,

I just wanted to inform you that I used your code to create a `go get`-able package for both Windows and non-Windows operating systems. See here for more details: https://github.com/xanzy/ssh-agent

As you can see I've put your license info in the appropriate files and also made a clear reference to your code in the [README.md](https://github.com/xanzy/ssh-agent/blob/master/README.md).

Hope you can appreciated the package :smiley:

Cheers,

Sander

**Comment by davidmz** [comment]
Thank you, that's good news!
